using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.IO;

namespace AssemblyParser.Utilities.Data
{
    class ReadInData
    {
        //data members

        private StreamReader fileStream;
        private String lineReader;

        //methods

        /// <summary>
        /// The data object which holds data generated by createData
        /// </summary>
        private List<int> data;

        /// <summary>
        /// The constructor of the ReadInData class
        /// </summary>
        public ReadInData(int arrayNumber)
        {
            createData(arrayNumber);
        }

        /// <summary>
        /// Populates the data object with the contents of the relatable file IF file exists
        /// </summary>
        /// <param name="arrayNumber">The File Number to be read</param>
        private void createData(int arrayNumber)
        {
            try
            {
                fileStream = new StreamReader(string.Format(@"./Utilities/Data/Arrays/array{0}.txt", arrayNumber));
                lineReader = fileStream.ReadLine();
                data = lineReader.Split(',').Select(int.Parse).ToList();
            }
            catch (Exception e) {
                Console.WriteLine("Execption encountered in ReadInData.createData \n \n {0} \n \n", e);
                Console.ReadKey();
                Environment.Exit(0);
            }
        }

        public List<int> getData()
        {
            return data;
        }

    }
}
